### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Mmhh, travis completed the job successfully. But the history on travis says that there are no jobs. Something in the .travis.yml? I did not change the security tokens...

**Comment by danieldietrich** [comment]
Coveralls.io on the other hand works like a charme

**Comment by ruslansennov** [comment]
It was a little experiment.
OK, I'll waiting for your settings :)

**Comment by danieldietrich** [comment]
later today or tomorrow - we will get it working!

**Pull request merged**
