### PR TITLE
following changes in parent project

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Oh, sorry. Probably I have to check the impact of changes now...

**Comment by ruslansennov** [comment]
you can't check all around :smile:

**Comment by danieldietrich** [comment]
Yeah, that would be overkill. There needs to be a maven parent which is built automatically with all sub-projects. With semantic versioning. All SNAPSHOTS have the same version... This would be best if number of projects grow.

**Comment by ruslansennov** [comment]
I believe it's unnecessary. <code>jackson-snapshot</code> shouldn't depends from <code>javaslang-snapshot</code>
But now is special development period with a lot of improvements (Linked collection etc.)

**Pull request merged**
